# Generated by Django 5.1.4 on 2024-12-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_username_libuser_name_alter_libuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="libuser",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
